import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, test } from 'node:test';
import { fileURLToPath } from 'node:url';

const scriptPath = fileURLToPath(
  new URL('./generate-manifest.mjs', import.meta.url),
);
const temporaryRoots = [];

after(async () => {
  await Promise.all(
    temporaryRoots.map((root) => rm(root, { recursive: true, force: true })),
  );
});

test('writes manifest entries in alphabetical order', async () => {
  const root = await createTemporaryRoot();

  await writeExample(root, 'use-loop', 'basic');
  await writeExample(root, 'create-loop', 'advanced');
  await runGenerator(root);

  assert.equal(
    await readFile(join(root, 'manifest.ts'), 'utf8'),
    `// Generated by scripts/generate-manifest.mjs. Do not edit.
import type { ComponentType } from 'react';

export type ExampleModule = { default: ComponentType };
export type ExampleLoader = () => Promise<ExampleModule>;

export const manifest = {
  'create-loop/advanced': () => import('./create-loop/advanced'),
  'use-loop/basic': () => import('./use-loop/basic'),
} satisfies Record<string, ExampleLoader>;

export type ExampleSlug = keyof typeof manifest;
`,
  );
});

test('reports a missing meta.ts file', async () => {
  const root = await createTemporaryRoot();
  const directory = join(root, 'use-loop');
  await mkdir(directory, { recursive: true });
  await writeFile(
    join(directory, 'basic.tsx'),
    `export default function Example() { return null; }\n`,
  );

  await assert.rejects(runGenerator(root), /use-loop\/meta\.ts is required/);
});

test('reports invalid example files and folders', async (context) => {
  await context.test('non-kebab-case example directory', async () => {
    const root = await createTemporaryRoot();
    await writeExample(root, 'useLoop', 'basic');

    await assert.rejects(
      runGenerator(root),
      /example directory "useLoop" must be kebab-case/,
    );
  });

  await context.test('non-kebab-case variant', async () => {
    const root = await createTemporaryRoot();
    await writeExample(root, 'use-loop', 'BasicExample');

    await assert.rejects(
      runGenerator(root),
      /use-loop\/BasicExample\.tsx must use a kebab-case file name/,
    );
  });

  await context.test('folder with no .tsx example files', async () => {
    const root = await createTemporaryRoot();
    const directory = join(root, 'use-loop');
    await mkdir(directory, { recursive: true });
    await writeFile(
      join(directory, 'meta.ts'),
      `export default { title: 'use-loop', description: 'Example', exports: ['useLoop'] };\n`,
    );

    await assert.rejects(
      runGenerator(root),
      /use-loop must contain at least one \.tsx example/,
    );
  });

  await context.test('example file without a default export', async () => {
    const root = await createTemporaryRoot();
    const directory = join(root, 'use-loop');
    await mkdir(directory, { recursive: true });
    await writeFile(
      join(directory, 'meta.ts'),
      `export default { title: 'use-loop', description: 'Example', exports: ['useLoop'] };\n`,
    );
    await writeFile(
      join(directory, 'basic.tsx'),
      `'use client';\nexport function Example() { return null; }\n`,
    );

    await assert.rejects(
      runGenerator(root),
      /use-loop\/basic\.tsx must have a default export/,
    );
  });

  await context.test(
    "example file without 'use client' at the start",
    async () => {
      const root = await createTemporaryRoot();
      const directory = join(root, 'use-loop');
      await mkdir(directory, { recursive: true });
      await writeFile(
        join(directory, 'meta.ts'),
        `export default { title: 'use-loop', description: 'Example', exports: ['useLoop'] };\n`,
      );
      await writeFile(
        join(directory, 'basic.tsx'),
        `export default function Example() { return null; }\n`,
      );

      await assert.rejects(
        runGenerator(root),
        /use-loop\/basic\.tsx must start with 'use client'/,
      );
    },
  );

  await context.test(
    'meta.ts with an empty title and exports list',
    async () => {
      const root = await createTemporaryRoot();
      const directory = join(root, 'use-loop');
      await mkdir(directory, { recursive: true });
      await writeFile(
        join(directory, 'meta.ts'),
        `export default { title: '', description: 'Example', exports: [] };\n`,
      );
      await writeFile(
        join(directory, 'basic.tsx'),
        `'use client';\nexport default function Example() { return null; }\n`,
      );

      await assert.rejects(
        runGenerator(root),
        /use-loop\/meta\.ts must include a title, a description, and at least one export/,
      );
    },
  );
});

async function createTemporaryRoot() {
  const root = await mkdtemp(join(tmpdir(), 'phase-examples-'));
  temporaryRoots.push(root);
  return root;
}

async function writeExample(root, exportName, variant) {
  const directory = join(root, exportName);
  await mkdir(directory, { recursive: true });
  await writeFile(
    join(directory, 'meta.ts'),
    `export default { title: '${exportName}', description: 'Example', exports: ['${exportName}'] };\n`,
  );
  await writeFile(
    join(directory, `${variant}.tsx`),
    `'use client';\nexport default function Example() { return null; }\n`,
  );
}

async function runGenerator(root) {
  const { spawn } = await import('node:child_process');

  await new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [scriptPath, root], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stderr = '';
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
    });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(stderr));
    });
  });
}
