// Generated by scripts/generate-manifest.mjs. Do not edit.
import type { ComponentType } from 'react';

export type ExampleModule = { default: ComponentType };
export type ExampleLoader = () => Promise<ExampleModule>;

export const manifest = {
  'create-loop/basic': () => import('./create-loop/basic'),
  'defer/basic': () => import('./defer/basic'),
  'presence/basic': () => import('./presence/basic'),
  'use-canvas/basic': () => import('./use-canvas/basic'),
  'use-loop/basic': () => import('./use-loop/basic'),
  'use-tween/basic': () => import('./use-tween/basic'),
  'when-visible/basic': () => import('./when-visible/basic'),
} satisfies Record<string, ExampleLoader>;

export type ExampleSlug = keyof typeof manifest;
